blog/models.py
from datetime import datetime

from application import db

# associaton table
tag_x_post = db.Table('tag_x_post',
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True),
    db.Column('post_id', db.Integer, db.ForeignKey('post.id'), primary_key=True)
)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    author_id = db.Column(db.Integer, db.ForeignKey('author.id'))
    title = db.Column(db.String(80))
    body = db.Column(db.Text)
    image = db.Column(db.String(36))
    slug = db.Column(db.String(255), unique=True)
    publish_date = db.Column(db.DateTime)
    live = db.Column(db.Boolean)

    author = db.relationship('Author',
        backref=db.backref('posts', lazy='dynamic'))

    category = db.relationship('Category',
        backref=db.backref('posts', lazy='dynamic'))

    tags = db.relationship('Tag', secondary=tag_x_post, lazy='subquery',
        backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, author, title, body, image=None, category=None,
        slug=None, publish_date=None, live=True):
        self.author_id = author.id
        self.title = title
        self.body = body
        self.image = image
        if category:
            self.category_id = category.id
        self.slug = slug
        if publish_date is None:
            self.publish_date = datetime.utcnow()
        self.live = live

    def __repr__(self):
        return '<Post %r>' % self.title

class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return self.name

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return self.name

blog/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, TextAreaField, FileField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask_wtf.file import FileAllowed

from blog.models import Category

def categories():
    return Category.query

class PostForm(FlaskForm):
    image = FileField('Image', validators=[
        FileAllowed(['jpg', 'png'], 'We only accept JPG or PNG images')
    ])
    title = StringField('Title', [
        validators.InputRequired(),
        validators.Length(max=80)
    ])
    body = TextAreaField('Content', validators=[validators.InputRequired()])
    category = QuerySelectField('Category', query_factory=categories,
        allow_blank=True)
    new_category = StringField('New Category')

blog/views.py
import os
import uuid

from flask import Blueprint, session, render_template, flash, redirect, url_for, request
from PIL import Image
from slugify import slugify

from application import db
from author.models import Author
from author.decorators import login_required
from blog.models import Category, Post, Tag
from blog.forms import PostForm
from settings import BLOG_POST_IMAGES_PATH

blog_app = Blueprint('blog_app', __name__)
POSTS_PER_PAGE = 5

@blog_app.route('/')
def index():
    page = int(request.values.get('page', '1'))
    posts = Post.query.filter_by(live=True).order_by(Post.publish_date.desc()) \
        .paginate(page, POSTS_PER_PAGE, False)
    return render_template('blog/index.html', posts=posts, title = 'Latest Posts')

@blog_app.route('/post', methods=('GET', 'POST'))
@login_required
def post():
    form = PostForm()
    tags_field = request.values.get('tags_field', '')

    if form.validate_on_submit():
        image_id = None

        if form.image.data:
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.png'
            file_path = os.path.join(BLOG_POST_IMAGES_PATH, file_name)
            Image.open(f).save(file_path)

            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 600, 'lg')
            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 100, 'sm')

        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            category = new_category
        else:
            category = form.category.data

        author = Author.query.get(session['id'])
        title = form.title.data.strip()
        body = form.body.data.strip()
        post = Post(
            author = author,
            title = title,
            body = body,
            image = image_id,
            category = category
        )

        _save_tags(post, tags_field)

        db.session.add(post)
        db.session.commit()

        slug = slugify(str(post.id) + '-' + post.title)
        post.slug = slug
        db.session.commit()

        flash('Article Posted')
        return redirect(url_for('.article', slug=slug))

    return render_template('blog/post.html',
        form = form,
        action = 'new',
        tags_field = tags_field
    )

@blog_app.route('/posts/<slug>')
def article(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    return render_template('blog/article.html', post=post)

@blog_app.route('/edit/<slug>', methods=('GET', 'POST'))
@login_required
def edit(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    form = PostForm(obj=post)
    tags_field = request.values.get('tags_field', _load_tags_field(post))

    if form.validate_on_submit():
        original_image = post.image
        original_title = post.title
        form.populate_obj(post)

        if form.image.data:
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.png'
            file_path = os.path.join(BLOG_POST_IMAGES_PATH, file_name)
            Image.open(f).save(file_path)

            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 600, 'lg')
            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 100, 'sm')
            post.image = image_id
        else:
            post.image = original_image

        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            post.category = new_category

        if form.title.data != original_title:
            post.slug = slugify(str(post.id) + '-' + form.title.data)

        _save_tags(post, tags_field)
        db.session.commit()
        flash('Article Edited')
        return redirect(url_for('.article', slug=post.slug))

    return render_template('blog/post.html',
        form = form,
        post = post,
        action = 'edit',
        tags_field = tags_field
    )

@blog_app.route('/delete/<slug>')
@login_required
def delete(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    post.live = False
    db.session.commit()
    flash('Article Deleted')
    return redirect(url_for('.index'))

@blog_app.route('/categories/<category_id>')
def categories(category_id):
    category = Category.query.filter_by(id=category_id).first_or_404()
    page = int(request.values.get('page', '1'))
    posts = Post.query.filter_by(category=category, live=True) \
        .order_by(Post.publish_date.desc()) \
        .paginate(page, POSTS_PER_PAGE, False)

    return render_template('blog/category_posts.html',
        posts = posts,
        title = category,
        category_id = category_id
    )

@blog_app.route('/tags/<tag>')
def tags(tag):
    tag = Tag.query.filter_by(name=tag).first_or_404()
    page = int(request.values.get('page', '1'))
    posts = tag.posts.filter_by(live=True) \
        .order_by(Post.publish_date.desc()) \
        .paginate(page, POSTS_PER_PAGE, False)
    
    return render_template('blog/tag_posts.html',
        posts = posts,
        title = 'Tag: ' + str(tag),
        tag = str(tag)
    )

def _image_resize(original_file_path, image_id, image_base, extension):
    file_path = os.path.join(original_file_path, image_id + '.png')
    image = Image.open(file_path)

    wpercent = (image_base / float(image.size[0]))
    hsize = int((float(image.size[1]) * float(wpercent)))
    image = image.resize((image_base, hsize), Image.ANTIALIAS)

    modified_file_path = os.path.join(original_file_path, image_id + '.' + extension + '.png')
    image.save(modified_file_path)
    return

def _save_tags(post, tags_field):
    post.tags.clear()
    for tag_item in tags_field.split(','):
        tag = Tag.query.filter_by(name=slugify(tag_item)).first()
        if not tag:
            tag = Tag(name=slugify(tag_item))
            db.session.add(tag)
        post.tags.append(tag)
    return post

def _load_tags_field(post):
    tags_field = ''
    for tag in post.tags:
        tags_field += tag.name + ', '
    return tags_field[:-2]

templates/blog/_article_list.html
<div class="post-list">
  {% for post in posts.items %}
  <div class="row post-item pt-3">
    <div class="col-md-9">
      <h5><a href="{{ url_for('blog_app.article', slug=post.slug) }}">{{ post.title }}</a></h5>
      <div class="post-body">{{ post.body[:220] }}</div>
      <div class="text-muted">Posted By: {{ post.author.full_name }} on {{
        post.publish_date.strftime('%Y-%m-%d') }}
        {% if post.category %}
        in <a href="{{ url_for('.categories', category_id=post.category.id) }}">
          {{ post.category.name }}</a> 
        {% endif %}
      </div>

    </div>
    <div class="col-3-md">
      {% if post.image %}
      <img src="{{ url_for('static', filename='images/uploads/' + post.image + '.sm.png') }}" class="img-thumbnail" />
      {% endif %}
    </div>
  </div>
  <hr />
  {% endfor %}
</div>

templates/blog/article.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">
  <div class="offset-md-2 col-md-8">
    {% include '_flashmessages.html' %}
    {% if post.image %}
    <div class="container pt-3">
      <img src="{{ url_for('static', filename='images/uploads/' + post.image + '.lg.png') }}" class="img-fluid" />
    </div>
    {% endif %}
    <h1 class="pt-3">{{ post.title }}</h1>
    {{ post.body|markdown }}
    <hr />
    <div class="text-muted">
      Posted by {{ post.author.full_name }} on {{ post.publish_date.strftime('%Y-%m-%d') }}
      {% if post.category %}
      in <a href="{{ url_for('.categories', category_id=post.category.id) }}">
        {{ post.category.name }}
      </a>
      {% endif %}
      &nbsp; [{% for tag in post.tags %}
        <a href="{{ url_for('.tags', tag=tag.name) }}">{{ tag }}</a>
        {% if not loop.last %},{% endif %}
      {% endfor %}]
      {% if session.id %}
        <a href="{{ url_for('.edit', slug=post.slug) }}">Edit</a>
        <a href="{{ url_for('.delete', slug=post.slug) }}">Delete</a>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/blog/category_posts.html
{% extends "base.html" %}

{% block title %}{{ title }} - {{ config['BLOG_NAME'] }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">
  <div class="offset-md-2 col-md-8 pt-5">
    {% include '_flashmessages.html' %}
    <h4>{{ title }}</h4>
    {% include 'blog/_article_list.html' %}
  </div>
</div>
<div class="row">
  <div class="offset-md-2 col-md-8 pt-5">
    {% if posts.has_prev %}
    <a href="{{ url_for('blog_app.categories', category_id=category_id, page=posts.prev_num) }}">&lt;&lt; Newer Posts</a>
    {% endif %}
    {% if posts.has_next %}
    <a href="{{ url_for('blog_app.categories', category_id=category_id, page=posts.next_num) }}">Older Posts  &gt;&gt;</a>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}

{% block title %}{{ title }} - {{ config['BLOG_NAME'] }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">
  <div class="offset-md-2 col-md-8 pt-5">
    {% include '_flashmessages.html' %}
    <h4>Latest Posts</h4>
    <div class="post-list">
      {% for post in posts.items %}
      <div class="row post-item pt-3">
        <div class="col-md-9">
          <h5><a href="{{ url_for('blog_app.article', slug=post.slug) }}">{{ post.title }}</a></h5>
          <div class="post-body">{{ post.body[:220] }}</div>
          <div class="text-muted">Posted By: {{ post.author.full_name }} on {{
            post.publish_date.strftime('%Y-%m-%d') }}
            {% if post.category %}
            in {{ post.category.name }}
            {% endif %}
          </div>

        </div>
        <div class="col-3-md">
          {% if post.image %}
          <img src="{{ url_for('static', filename='images/uploads/' + post.image + '.sm.png') }}" class="img-thumbnail" />
          {% endif %}
        </div>
      </div>
      <hr />
      {% endfor %}
    </div>

  </div>
</div>

<div class="row">
  <div class="offset-md-2 col-md-8 pt-5">
    {% if posts.has_prev %}
    <a href="{{ url_for('blog_app.index', page=posts.prev_num) }}">&lt;&lt; Newer Posts</a>
    {% endif %}
    {% if posts.has_next %}
    <a href="{{ url_for('blog_app.index', page=posts.next_num) }}">Older Posts &gt;&gt;</a>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/blog/post.html
{% extends "base.html" %}

{% block title %}Home - {{ config['BLOG_NAME'] }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">
  <div class="offset-md-2 col-md-8">

    {% if action == "new" %}
    <h3>New Blog Post</h3>
    {% else %}
    <h3>Edit Blog Post</h3>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    {% if action == "new" %}
    <form method="POST" action="{{ url_for('.post') }}" enctype="multipart/form-data" role="form">
    {% else %}
    <form method="POST" action="{{ url_for('.edit', slug=post.slug) }}" enctype="multipart/form-data" role="form">
    {% endif %}
      {{ form.hidden_tag() }}
      
      {% if post and post.image %}
      <img src="{{ url_for('static', filename='images/uploads/' + post.image + '.sm.png') }}"
        class="img-thumbnail" />
      {% endif %}

      {{ render_field(form.image, class='form-control') }}
      {{ render_field(form.title, class='form-control') }}
      {{ render_field(form.body, class='form-control', rows=10) }}
      {{ render_field(form.category, class='form-control') }}
      {{ render_field(form.new_category, class='form-control') }}
      <div class="form-group">
        <label for="tags_field">Tags</label>
        <input class="form-control" id="tags_field" name="tags_field"
          type="text", value="{{ tags_field }}">
      </div>

      {% if action == "new" %}
      <button type="submit" class="btn btn-primary">Post</button>
      {% else %}
      <button type="submit" class="btn btn-primary">Update</button>
      {% endif %}
    </form>
  </div>
</div>

{% endblock %}

templates/blog/tag_posts.html
{% extends "base.html" %}

{% block title %}{{ title }} - {{ config['BLOG_NAME'] }}{% endblock %}

{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

<div class="row">
  <div class="offset-md-2 col-md-8 pt-5">
    {% include '_flashmessages.html' %}
    <h4>{{ title }}</h4>
    {% include 'blog/_article_list.html' %}
  </div>
</div>
<div class="row">
  <div class="offset-md-2 col-md-8 pt-5">
    {% if posts.has_prev %}
    <a href="{{ url_for('blog_app.tags', category_id=tag, page=posts.prev_num) }}">&lt;&lt; Newer Posts</a>
    {% endif %}
    {% if posts.has_next %}
    <a href="{{ url_for('blog_app.tags', category_id=tag, page=posts.next_num) }}">Older Posts &gt;&gt;</a>
    {% endif %}
  </div>
</div>
{% endblock %}